version: 2.0

defaults: &defaults
  docker:
    - image: circleci/android:api-27-alpha
  working_directory: ~/tivi
  environment:
    JAVA_TOOL_OPTIONS: "-Xmx1024m"
    GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Dkotlin.incremental=false"
    TERM: dumb

update_sdk: &update_sdk
  name: Update SDK
  command: |
    mkdir "$ANDROID_HOME/licenses" || true
    echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
    echo "84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
    sdkmanager "platform-tools" "platforms;android-27"

jobs:
  build:
    <<: *defaults
    steps:
      - run:
          <<: *update_sdk
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew dependencies
      - run:
          name: Decrypt secrets
          command: signing/setup.sh $ENCRYPT_KEY
      - run:
          name: Check and assemble APKs
          command: ./gradlew check assemble dependencyUpdates
      - run:
          name: Cleanup secrets
          command: signing/cleanup.sh
      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - store_artifacts:
          path: app/build/outputs/apk
          destination: apks
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_artifacts:
          path: build/dependencyUpdates
          destination: dependencyUpdates
      - store_test_results:
          path: app/build/test-results
      - persist_to_workspace:
          root: .
          paths:
            - build
            - app/build
  deploy_to_play:
    <<: *defaults
    steps:
      - run:
          <<: *update_sdk
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - attach_workspace:
          at: ~/tivi
      - run:
          name: Decrypt secrets
          command: signing/setup.sh $ENCRYPT_KEY
      - run:
          name: Deploy to Alpha channel
          command: ./gradlew publishRelease
      - run:
          name: Cleanup secrets
          command: signing/cleanup.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy_to_play:
          requires:
            - build
          filters:
            branches:
              only: deploy
